bkerler/mtkclient

- mtk
* Commit https://github.com/bkerler/mtkclient/commit/bef2d8efd0750c111904a437ef571b081deb09fd seems to break the init
function when no preloader is provided at all (using the --preloader option).
> mtk: init: don't crash if no preloader was supplied

- mtk
I got an exception when I tried to write whole flash and none method writeflash expect the parameter partitionname so I removed it and write whole flash start.
> partitionname is not expected in writeflash removed

- mtkclient/config/brom_config.py
MT6781 is Helio G96 while MT6761 is Helio A22
> Set Correct name for mt6781

- README.md
- missing `python3-pip`
- `libusb1.0` does not exist in the latest version of Ubuntu. Use `libusb-1.0-0` instead
> Fix linux deps

- mtkclient/Library/utils.py
- mtkclient/Library/xflash_ext.py
We can find other function (not 'mmc_set_part_config'). And this can make 'user' or 'boot1' 1st sector is corrupt.
Added additional conditions for function search.
> Fix some trouble, that can make phone brick, when rpmb is readed.

- mtkclient/Library/Connection/devicehandler.py
Fix Launching of GUI
file is using edl instead of the required mtk.  
This is in turn causing an eldclient error and preventing the GUI from launching
> Fix GUI Launching

- mtkclient/Library/mtk_preloader.py
- mtkclient/config/brom_config.py
- mtkclient/config/mtk_config.py
When I tried running mtkclient with my device I've got the following log:
```
MTK Flash/Exploit Client V1.55 (c) B.Kerler 2018-2022
Preloader - Status: Waiting for PreLoader VCOM, please connect mobile
Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...
Preloader
Preloader - [LIB]: Status: Handshake failed, retrying...
Port - Device detected :)
Preloader - 	CPU:			MT6575/77()
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0xc0000000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0xc2001000
Preloader - 	Var1:			0xa
Preloader - Disabling Watchdog...
usb_class - USBError(32, 'Pipe error')
Traceback (most recent call last):
File "/mnt/hdd/soft/mtkclient/mtk", line 698, in <module>
mtk = Main(args).run()
File …
```
> Fixes and improvements for mt6575, mt6577. New generic write function. setreg_disablewatchdog optimization.

- setup.py
I found pyserial is needed for installation.
This PR adds the dependency.﻿
> add pyserial dependency

- mtkclient/Library/daconfig.py
- mtkclient/config/usb_ids.py
* Commit https://github.com/bkerler/mtkclient/commit/e76c4704719f996b3c39b0fc32d33fd0472359a6 fixed support for MT6592. However, the hw_code check added in
that change causes the tool to fail when trying to acquire the loader config:
- DAconfig - [LIB]: No da_loader config set up
* Removing the check seems to fix the problem (the tool configures the loader
correctly). I'm not sure what the point of the check is (there is no loader
with 5.1648 in its name), but since it seems to work fine without it, nuke
it.
> Various updates

- mtk.bat
- mtk_gui.bat
We can use it anywhere by setting the PATH to MTKClient in the environment variable.
I used to have a hard time using it on Windows every time, but this solved it all !
> Add batch files

- mtk.bat
If there are spaces in the directory path, passing the path as an argument will cause the command line to fail (with an error that such directory does not exist) :)
> Update mtk.bat (Fixed Crash)

- pyproject.toml
- setup.cfg
- setup.py
The build error:
```  parsed = self.parsers.get(option_name, lambda x: x)(value)
validate_pyproject.api.load_builtin_plugin defines `tool.distutils` schema
validate_pyproject.api.load_builtin_plugin defines `tool.setuptools` schema
Traceback (most recent call last):
File "/home/vilez/Harddisk/mtkclient/setup.py", line 4, in <module>
setup(
File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
return distutils.core.setup(**attrs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
dist.parse_config_files()
File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 898, in parse_config_files
pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
File …
```
> Fix build error after latest pyproject.toml update. Replace license_file parameter with license_files (license_file parameter is deprecated) 

- README.md
- mtk
- mtkclient/Library/DA/mtk_da_handler.py
- mtkclient/Library/Filesystem/mtkdafs.py
- requirements.txt
This pull request adds a command line option to mount the internal flash and it's separate partitions as a FUSE filesystem. This can be useful for modifying or repairing devices that refuse to boot, without making a full flash dump. 
A FUSE filesystem is also relatively easy to implement, as all the primitives needed to read and write to arbitrary locations are already implemented.
> Add option to mount the internal flash as a FUSE filesystem

- mtkclient/Library/DA/mtk_da_handler.py
If logs don't exist for some reason, we don't need to trip up when deleting them, which prevents proper device shutdown.
> Fix FileNotFound exception in mtk reset

- pyproject.toml
Fix ModuleNotFoundError
System environment (not required):
ArchLinux
Python 3.12
pip 24.0
Bug Reproduction Steps:
```bash
$ python -m venv test
$ cd test 
$ . bin/activate
$ git clone --depth=1 https://github.com/bkerler/mtkclient
Cloning into 'mtkclient'...
remote: Enumerating objects: 1147, done.
remote: Counting objects: 100% (1147/1147), done.
remote: Compressing objects: 100% (491/491), done.
remote: Total 1147 (delta 768), reused 814 (delta 647), pack-reused 0
Receiving objects: 100% (1147/1147), 19.28 MiB | 5.82 MiB/s, done.
Resolving deltas: 100% (768/768), done.
$ cd mtkclient
$ pip install .                                              
Looking in indexes: https://mirrors.cernet.edu.cn/pypi/web/simple, https://mirrors.cloud.tencent.com/pypi/simple, …
```
> Fix ModuleNotFoundError

- mtkclient/Library/mtk_class.py
- Fixes:
EP_OUT = self.cdc.EP_OUT.write
^^^^^^^^^^^^^^^
AttributeError: 'serial_class' object has no attribute 'EP_OUT'
> mtk_class: Use serial_handshake if serialportname provided

- .github/workflows/python-app.yml
- ubuntu 24.04 is available ubuntu-latest still points to 22.04 
- upgrade setup-python action to v5
> update GitHub actions

- mtkclient/Library/pltools.py
This pull request addresses an issue in the `runpayload` method where the if statement was incorrectly comparing the acknowledgement value with itself, which always returns true. The comparison has been corrected to properly compare the response acknowledgement (`response_ack`) with the expected `ack` value.
- Corrected the if statement from `if ack == ack:` to `if response_ack == ack:`.
> Fix incorrect comparison in runpayload method

- mtkclient/Library/DA/mtk_da_handler.py
This PR skips BROM exploitation when the user-supplied preloader is given through a command line argument.
Through this change, BROM patched, but SBC/SLA/DAA disabled machines BROM mode can be supported. (i.e. MD-PH-001)
> Skip BROM exploitation when preloader is given through commandline argument

- mtkclient/Library/DA/xflash/extension/xflash.py
None causes error for wrong type expected instead of empty string.
> Fix expected type of default parameter for filename

- mtkclient/config/brom_config.py
I found the HW code and some register addresses for the MT6880 / MT6890. The values were discovered by interacting with the BROMs on a T-Mobile / Quanta D53 5G mobile hotspot (MT6890) and a Dell DW5931e / Fibocom FM350-GL WWAN card (MT6880).
> Add MT6890 information

- mtkclient/Library/DA/mtk_da_handler.py
This pull request fixes the following error encountered while patching vbmeta on non-A/B devices:
```
Preloader - 	CPU:			MT6761/MT6762/MT3369/MT8766B(Helio A20/P22/A22/A25/G25)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0x25
Preloader - Disabling Watchdog...
Preloader - HW code:			0x717
Preloader - Target config:		0x0
Preloader - 	SBC enabled:		False
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		False
Preloader - 	SWJTAG enabled:		False
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		False
Preloader - …
```
> Fix partition slot handling in vbmeta patching for non-A/B devices

- mtkclient/Library/Hardware/hwcrypto_dxcc.py
- mtkclient/Library/Hardware/seccfg.py
Fix issue #1345 and probably others related to MediaTek Helio P90T (MT8788).
For SecCfgV4, trying to parse an algorithm using legacy code before the new method (hwtype V3) can have the unintended of altering the resulting hash. Trying to parse for SW or V3 before V4 and V2 have fixed it.
Suggestion: review the underlying code to identify the root cause as of why the legacy code has a side effect of altering the resulting hash of algorithm not using the legacy code.
> seccfg parse: legacy algorithms are now tried last to fix parse hwtype=V3

- README.md
> Add venv for Arch Linux

- README.md
As from title, openssl 1.1.1 seems to be required so I think that it can be added to the setup for windows as python scrypt dependency needs it
> I added openssl 1.1.1 on mtkclient setup description for windows. Without scrypt dependency install fails to build during the install

- mtk_gui.py
- mtkclient/gui/eraseFlashPartitions.py
- mtkclient/gui/readFlashPartitions.py
- mtkclient/gui/writeFlashPartitions.py
- pyproject.toml
- requirements.txt
- shell.nix
This library has been merged into the standard library back in Python 3.3, so we can safely use it without a dependency.
> Replace mock dependency with unittest.mock

- mtkclient/Library/DA/xflash/xflash_lib.py
For NAND the minimum read/write size is usually larger than the default 512 bytes. Make functions aware of the page size detected.
> XFlash: export the detected page size for NAND storage

- mtkclient/Library/DA/xflash/xflash_lib.py
DA extensions are loaded starting from 640MB of the DRAM. That causes devices with less memory to hang on the `boot_to` call:
```
DAXFlash - Extensions were accepted. Jumping to extensions...
DAXFlash
DAXFlash - [LIB]: Stage was't executed. Maybe dram issue ?.
```
Fix it by adjusting the load address.
(I see no reason to decrease it even further but at some point we might overwrite working memory used by the DA.)
> XFlash: load DA extensions below the 256MB address mark
